version: "3.8"

services:
  frontend:
    build:
      context: ./qr-code-frontend
      dockerfile: Dockerfile
    image: devshah95/aws-infrastructure-project-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./qr-code-backend
      dockerfile: Dockerfile
    image: devshah95/aws-infrastructure-project-backend:latest
    ports:
      - "8000:8000"
